spring:
  application:
    name: GameListServer

  datasource:
    url: jdbc:mysql://mysql:3306/game_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gameuser
    password: gamepass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 8084
  servlet:
    context-path: /game-service
  tomcat:
    uri-encoding: UTF-8
